
<?php echo $this->headTitle(); ?>


<h1>Show Profile</h1><br>
<div id="message_box">
    <?php
    if (isset($this->messages[0]))
        echo $this->messages[0];
    ?>
</div>
<table>
    <thead>
        <tr>
            <th>Show Profile</th> 
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Mã sinh viên: </td>
            <td><?php echo $this->escape($this->student->getStudentId()) ?></td>
        </tr>
        <tr>
            <td>Họ và tên: </td>
            <td><?php echo $this->escape($this->student->getStudentName()) ?></td>
        </tr>
        <tr>
            <td>Ngày sinh: </td>
            <td><?php echo $this->escape($this->student->getDateOfBirth()) ?></td>
        </tr>
        <tr>
            <td>Giới tính: </td>
            <td><?php
                if (1 == $this->student->getGender())
                    echo "Nam";
                else
                    echo "Nữ";
                ?></td>
        </tr>
        <tr>
            <td>Số điện thoại: </td>
            <td><?php echo $this->escape($this->student->getPhone()) ?></td>
        </tr>
        <tr>
            <td>Địa chỉ: </td>
            <td><?php echo $this->escape($this->student->getAddress()) ?></td>
        </tr>

    </tbody>
</table>


